<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>gobtninvsearch</description>
   <name>btnsearchinv</name>
   <tag></tag>
   <elementGuidId>e613f8fa-2151-487f-b2ac-872d82642783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@id='invoiceSearchGoButton'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@id='invoiceSearchGoButton'])[2]</value>
      <webElementGuid>44b6090c-f4da-4282-8922-fcc186758e36</webElementGuid>
   </webElementProperties>
</WebElementEntity>
