<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>gobtninvsearch</description>
   <name>btnsearchinv</name>
   <tag></tag>
   <elementGuidId>e613f8fa-2151-487f-b2ac-872d82642783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='invoiceSearchGoButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='invoiceSearchGoButton']</value>
      <webElementGuid>f62d6085-1a21-4c38-9aa5-304dc606d262</webElementGuid>
   </webElementProperties>
</WebElementEntity>
