<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>invoicelink</description>
   <name>invoicelnk</name>
   <tag></tag>
   <elementGuidId>e80630dd-280f-47de-9084-f0412e4f5cfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='goToInvoiceDetail-7378363046']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='goToInvoiceDetail-7378363046']</value>
      <webElementGuid>51befeb8-f7b4-4700-a607-04c7e3fb193d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
