<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>invoicelink</description>
   <name>invoicelnk</name>
   <tag></tag>
   <elementGuidId>e80630dd-280f-47de-9084-f0412e4f5cfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='goToInvoiceDetail-7220716952']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='goToInvoiceDetail-7220716952']</value>
      <webElementGuid>ad1124f8-5d4d-468a-abcb-0a7183fc6052</webElementGuid>
   </webElementProperties>
</WebElementEntity>
