<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Kinray-RegressionSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f4ab7d34-0307-447a-ad47-ea03e6c8ff53</testSuiteGuid>
   <testCaseLink>
      <guid>a96c2745-7eb8-43d4-9185-300d02d6d26a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_InvoiceHistory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00187208-ff6c-49c7-a3a3-9d13c938df82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b589d7b-c6a1-4a45-b670-00ad485a9ade</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateCSOSOrderhistory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5a065c33-3204-4882-83c8-18b12cc834f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateEndtoEnd_submitorder</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d097fbf-643d-41d3-9633-744c23e3382e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96193aee-0b6d-4e6f-9a15-0e29d8a4f1ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3d959e4-a4bd-4491-b861-94ed9dbfc034</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateHelpPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d91e8585-b19a-49c1-b6b4-1c6082f1ded5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateReturnStatus</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>29e986cc-65e6-4ebc-9984-3f0a8cb98cba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_Validate_OrderHistory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d649ff68-3b30-45e1-80cb-5fe67bbb1373</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35706ed2-3971-4c40-8472-395aef164342</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateTrackTrace</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>abce105e-b909-400d-9bc8-486a53b836d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateBackOrderItems</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0f1f1262-2128-4d4a-9856-da1cf2b64301</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateComposeNewMessage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>01992e80-6d31-4467-85e8-543a44bfaa5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateStatement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a6deb908-ed2c-4c61-87e1-c86a46c128aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ProductRecommendation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>236d6271-7223-4f3c-b79a-275dc1f7d22d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateReturnsHelpPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08b57c48-53df-4812-8b35-de017a1d85ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93cddacb-6926-4a13-a404-6f78c64672eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateCsosHelpPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21aa9eb8-39ce-49eb-ad7c-4a3b5fa3fa16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>688509e2-21d3-4a1e-b8c2-ea37c258d047</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_WebAccountSettings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a870de26-51ee-4494-81ec-eb6889aba2fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3030c430-c45a-4efb-94f7-a83888643665</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Kinray Test Cases/TS_ValidateC2Orders</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c79f66-f02b-4988-82e5-a69dda5bfe15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8bd35a2-ac29-4875-b16f-b75d3a7aba3d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
