<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>ParMed-RegressionSuite</description>
   <name>ParMed-RegressionSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d8b86ee1-0598-4059-befa-0669bf61ef85</testSuiteGuid>
   <testCaseLink>
      <guid>d7a022f2-952c-4892-a0d8-017f140d6470</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ParMed Test Cases/TS_ValidateEndtoEnd_submitorder</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daa51694-de07-4686-8392-3dc7658a6794</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fd2acc4-17c0-4c40-9a23-c631b824d245</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dbf56438-97ff-4d30-94e8-17784a2dace2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ParMed Test Cases/TS_ValidateCategoriesCC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a62ebd32-7a88-45df-a074-311d0975ec70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bcb8186d-b4d7-48ed-b8b3-091692442c61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ParMed Test Cases/TS_ValidateCategoriesPF</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
