<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DispilItem</description>
   <name>DispilItem</name>
   <tag></tag>
   <elementGuidId>a4657080-9771-4fa5-b41b-8228ea6c12ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(text(),&quot;DISPILL&quot;)])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(text(),&quot;DISPILL&quot;)])[1]</value>
      <webElementGuid>ffe5fef8-de09-477c-971c-c857f32d6dd4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
