<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>ea258548-8618-450c-823c-fbdf96df7356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#polist-popup-bottom-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='polist-popup-bottom-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08317c0c-ba88-47a9-8c81-ebf8e760a0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-kinray</value>
      <webElementGuid>6fc3d6f6-edcc-408e-9de6-7862540513bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>polist-popup-bottom-close</value>
      <webElementGuid>624904b5-90dc-4706-8994-ca72e0902211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6e9421f-3362-42e8-8b3b-e9e23703da6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Update</value>
      <webElementGuid>e3b2e9f8-36bd-4129-ac51-620c64ca157b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/kinray-product-alert-popup[@class=&quot;ng-star-inserted&quot;]/mat-dialog-actions[@class=&quot;row justify-content-center mat-dialog-actions&quot;]/button[@id=&quot;polist-popup-bottom-close&quot;]</value>
      <webElementGuid>81e689d1-b948-45cc-bacf-cf150cfe5fa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='polist-popup-bottom-close']</value>
      <webElementGuid>55fe1dac-f4dc-4aea-8532-05ece9b93598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/kinray-product-alert-popup/mat-dialog-actions/button</value>
      <webElementGuid>2f1756ce-4471-446d-af98-0db23abd349f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Either update the quantity OR click Cancel to leave the order(s) as-is in the cart.'])[1]/following::button[1]</value>
      <webElementGuid>a497f7c8-b93d-4750-bf60-d85983968760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to existing order'])[1]/following::button[1]</value>
      <webElementGuid>eacad895-bafb-4776-8ef7-77ee3ce4866d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>2a7611f2-2d43-4456-8884-fee4b1d680c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>dab69493-e7e4-436c-a442-2c9d8e022daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/button</value>
      <webElementGuid>46daa53d-8f24-4487-909d-971131ce3e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'polist-popup-bottom-close' and @type = 'button' and (text() = ' Update' or . = ' Update')]</value>
      <webElementGuid>0f2ce3f5-e793-4d71-b49f-e0a978183921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
