<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdvWindow</name>
   <tag></tag>
   <elementGuidId>13938f41-a4ae-40b3-9fbf-0adf7b395a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='btn-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='btn-close']</value>
      <webElementGuid>7aaf90d6-55f4-463a-b483-5dd20b87ea71</webElementGuid>
   </webElementProperties>
</WebElementEntity>
