<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_852166052</name>
   <tag></tag>
   <elementGuidId>b22c6f2b-76ec-4481-9e9f-cbc7cf48ae56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='goToOrderDetail-852166052']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#goToOrderDetail-852166052</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>493e9107-6219-42f2-81ff-d3d77e5cc4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline-text</value>
      <webElementGuid>b4cf95da-865b-4da0-b624-89c7ed145204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goToOrderDetail-852166052</value>
      <webElementGuid>4b0b6c14-f8b3-4d8e-acdf-2d27910f4369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>852166052</value>
      <webElementGuid>e02459b9-8868-44c2-a2c6-5db22b7ccfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goToOrderDetail-852166052&quot;)</value>
      <webElementGuid>b518a9a0-94a2-4cfa-944d-935abbabfed8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='goToOrderDetail-852166052']</value>
      <webElementGuid>42044164-938e-48e1-a859-c5c8518ff32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-table[@id='purchaseOrderHistory']/mat-row/mat-cell/a</value>
      <webElementGuid>cba6a3a8-da35-4072-9401-9f0896672fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'852166052')]</value>
      <webElementGuid>af0a8580-09fc-47af-b434-49768218eecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO# :'])[1]/following::a[1]</value>
      <webElementGuid>0252f999-c090-4aa0-a253-248eb816cb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By'])[1]/following::a[1]</value>
      <webElementGuid>78f843e1-fdac-4e51-9c93-09424f2f5858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation # :'])[1]/preceding::a[1]</value>
      <webElementGuid>0b9b3e98-10fe-4bd1-bb85-74b13faa1941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='852166052']/parent::*</value>
      <webElementGuid>f96a00e3-6692-4c32-b2cc-25f589197887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell/a</value>
      <webElementGuid>cdd18186-6690-4926-96ef-ec2adedcb1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'goToOrderDetail-852166052' and (text() = '852166052' or . = '852166052')]</value>
      <webElementGuid>f6b98b44-b37d-42c0-afb3-7884bace87a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
