<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEARCH</name>
   <tag></tag>
   <elementGuidId>9d40d763-a07d-41a8-953b-bb3d6d4bbf36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='orderHistorySearchGoButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#orderHistorySearchGoButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d3a7446-dce1-4027-93a0-ce020fa398e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-kinray btn-sm orderHistory-btn</value>
      <webElementGuid>f34d14bd-c26f-4ce5-8b23-00fd526e1495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderHistorySearchGoButton</value>
      <webElementGuid>fecf3eee-f8ec-45b0-8275-881870142391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SEARCH </value>
      <webElementGuid>75bc30eb-3af3-4a1b-a0d0-9044aeeb0176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderHistorySearchGoButton&quot;)</value>
      <webElementGuid>b0540a3f-1ae9-4a76-b1a7-6af91dc90568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='orderHistorySearchGoButton']</value>
      <webElementGuid>bf96a121-392c-4ab3-b3bb-6c1a7fd28368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='orderHistorySearchForm']/div/div[3]/button</value>
      <webElementGuid>e34f09f4-0c2f-4ec7-8533-ace9896dc797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/following::button[2]</value>
      <webElementGuid>08778176-5f88-41f4-9940-4fb44546c08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Order by:'])[1]/following::button[2]</value>
      <webElementGuid>34a825ae-2702-4f83-8943-b520092d5c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Order #'])[1]/preceding::button[1]</value>
      <webElementGuid>363b0bae-1f49-4e93-9523-08b22de63d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation #'])[1]/preceding::button[2]</value>
      <webElementGuid>38b6c47b-0b0b-4a66-8e17-4b060efe4a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>be93068c-0a89-4b52-82bb-1eb9892e07d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>10d6b48d-e04d-48ae-9b8d-c3df158d5c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'orderHistorySearchGoButton' and (text() = ' SEARCH ' or . = ' SEARCH ')]</value>
      <webElementGuid>e2f12e6a-23f2-4e3b-9e42-914b71e85c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
