<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_itemORPoNumber</name>
   <tag></tag>
   <elementGuidId>87222a34-c2ea-437c-9d88-3474a8ad02b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchItemORPoNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchItemORPoNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8edece6-5af9-426b-9560-d7c7c262d37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>584e656b-8fc7-4626-8377-daca4d4e3c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control prod-desc-input input-boder-zero ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>dbb274c5-639f-4863-bada-deadd243ffa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchItemORPoNumber</value>
      <webElementGuid>223360f5-5666-4d3f-a533-6a1932d0449a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemorponumber</name>
      <type>Main</type>
      <value>ngModel</value>
      <webElementGuid>57b96b47-2fdf-4db3-abc2-ad7d3af60abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemORPoNumber</value>
      <webElementGuid>08edd95a-19e2-4c55-994c-7f1c442720a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1915268f-bcb3-412d-841f-252dabc6a4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchItemORPoNumber&quot;)</value>
      <webElementGuid>76f7cf3b-74ec-4915-b2dd-ceb4d011c704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchItemORPoNumber']</value>
      <webElementGuid>3ab547ab-4064-462e-8315-5c179ddaa8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='orderHistorySearchForm']/div/div[2]/input</value>
      <webElementGuid>ec8d1ffd-86c0-492e-9824-aa6b0b9b2c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>69f115a6-5c6f-4786-8176-e89b2c43da04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchItemORPoNumber' and @name = 'itemORPoNumber' and @type = 'text']</value>
      <webElementGuid>1339cd03-becd-45a8-a9f4-09f3c86ad61b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
