<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>C2ItemId</name>
   <tag></tag>
   <elementGuidId>a8bc4dd0-6d51-4b9f-babd-419267dd013b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-cell[contains(text(),'4981130')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-cell[contains(text(),'5709787')]</value>
      <webElementGuid>ab61b744-3cb2-4839-b500-3d6fcc787421</webElementGuid>
   </webElementProperties>
</WebElementEntity>
