<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputC2</name>
   <tag></tag>
   <elementGuidId>1bea475f-f221-4858-a207-022cb15fe605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'poNum')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'poNum')]</value>
      <webElementGuid>c73eec36-92b4-49aa-8d5e-d9c56aef4503</webElementGuid>
   </webElementProperties>
</WebElementEntity>
