<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>showBtn</description>
   <name>showBtn</name>
   <tag></tag>
   <elementGuidId>229c4fa9-ca42-4dac-86bb-fb6993e7a897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='orderClickTag']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='orderClickTag']</value>
      <webElementGuid>6dd0c595-ca75-483a-930c-fbcc2046e4dc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
