<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>BtnAccount</description>
   <name>BtnAccount</name>
   <tag></tag>
   <elementGuidId>f22067d6-04ae-49e2-baed-c3b37401d0ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='navbarDropdownMenuLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='navbarDropdownMenuLink']</value>
      <webElementGuid>3ce7ccfb-cdb1-4285-9fc1-0f03c8bd4571</webElementGuid>
   </webElementProperties>
</WebElementEntity>
