<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drpDwnWebAccount</name>
   <tag></tag>
   <elementGuidId>cd5da87c-52f6-4e0c-b5cc-d73c5c4dd6cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='webSettingLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='webSettingLink']</value>
      <webElementGuid>a1d4fadb-6072-4f92-9ed0-85a1fd7a54d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
