<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblregualr</name>
   <tag></tag>
   <elementGuidId>a28ada31-515f-465d-a3f3-7e92a0fa7b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h3[@id='Regular']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h3[@id='Regular']</value>
      <webElementGuid>dbb01add-90c9-4bf9-b677-7e2d07909dd0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
