<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>MenuFluCareLnk</description>
   <name>MenuFluCareLnk</name>
   <tag></tag>
   <elementGuidId>aad7068f-2cfd-4188-93b6-0b98134316d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='flucare']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='flucare']</value>
      <webElementGuid>31e244b3-ec44-41b1-a51f-c7c2c3a5910e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
