<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ordersearchbtn</name>
   <tag></tag>
   <elementGuidId>e3d4dd86-ae85-43e4-8012-8585c93a0db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='orderHistorySearchGoButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='orderHistorySearchGoButton']</value>
      <webElementGuid>0dce48d8-4619-4a04-97c5-d807c0c233b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
