<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ordersearchhistory</description>
   <name>ordersearchtext</name>
   <tag></tag>
   <elementGuidId>1f0c1a17-bc35-4859-9e37-ae5426eca35d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='searchItemORPoNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='searchItemORPoNumber']</value>
      <webElementGuid>82c9246f-3bb5-4188-9e8e-23180ec70300</webElementGuid>
   </webElementProperties>
</WebElementEntity>
