<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchbtn</name>
   <tag></tag>
   <elementGuidId>845f211d-49cb-4432-a585-52c62f153834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@class='search-btn']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='search-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@class='search-btn']</value>
      <webElementGuid>a046aabc-a32b-4a31-9bfb-51b8be7cb98b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
