<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuContactUs</name>
   <tag></tag>
   <elementGuidId>3ebf805e-471d-41ac-ad6e-a0e86b5e1a18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='nav-contact-us']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='nav-contact-us']</value>
      <webElementGuid>e94f6049-3076-4f9a-9ce3-a32f53c3cdec</webElementGuid>
   </webElementProperties>
</WebElementEntity>
