<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Categories</description>
   <name>Categories</name>
   <tag></tag>
   <elementGuidId>fdb2911a-777a-46be-96d8-60f3916c5730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nav-categories']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
