<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dispil</name>
   <tag></tag>
   <elementGuidId>058c3993-8ac3-4b13-8b99-dac970371efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='nav-dispill']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='nav-dispill']</value>
      <webElementGuid>6596781e-dcde-4928-9c2b-23adfa9c9900</webElementGuid>
   </webElementProperties>
</WebElementEntity>
