<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuWatchList</name>
   <tag></tag>
   <elementGuidId>f9a2050a-51c8-4336-b47b-0b3419bb518b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='nav-watchList']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='nav-watchList']</value>
      <webElementGuid>58979b77-6361-4961-992e-cfd111f1df9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
