<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuProductCatalog</name>
   <tag></tag>
   <elementGuidId>165d8b70-31fa-4757-809d-41e4a77a7b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='nav-product-catalog']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='nav-product-catalog']</value>
      <webElementGuid>07acd005-ef4a-4372-b5e9-929df78584e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
