<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuSubscriptions</name>
   <tag></tag>
   <elementGuidId>ada73ec7-7342-4d2a-9931-90b9dfc4f82c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='nav-my-subscriptions']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='nav-my-subscriptions']</value>
      <webElementGuid>42d4a3ce-a781-4a46-83bb-93aff210b94c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
