<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuManageCreditCards</name>
   <tag></tag>
   <elementGuidId>c7825756-94cc-4c88-93da-54fe898a9387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='nav-manage-cards']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='nav-manage-cards']</value>
      <webElementGuid>e74d8b60-2017-47e9-ba5f-07a448fb2346</webElementGuid>
   </webElementProperties>
</WebElementEntity>
