<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ReturnsHelp</description>
   <name>ReturnsHelpMenu</name>
   <tag></tag>
   <elementGuidId>749d1ef7-6b24-4974-878c-8e62969d3f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='returns-help']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='returns-help']</value>
      <webElementGuid>d3792fba-b722-46a2-ad38-6a354177d41a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
